name: Deploy NGINX Server
on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a fresh Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Gets the latest code from the repository

    - name: Set up SSH connection
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.INSTANCE_IP }} << EOF
          cd /var/www/html
          git pull origin main
          sudo systemctl restart nginx
        EOF
      env:
        INSTANCE_IP: ${{ secrets.INSTANCE_IP }}  # Public IP of the EC2 instance
        AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}  # Stored private SSH key for authentication

    - name: Verify NGINX status
      run: |
        ssh -i key.pem ubuntu@${{ secrets.INSTANCE_IP }} "sudo systemctl status nginx"
